# Form implementation generated from reading ui file 'reg1.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
import os

from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setEnabled(True)
        Dialog.resize(442, 515)
        Dialog.setStyleSheet("background-color: rgb(45, 44, 44);")
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setGeometry(QtCore.QRect(110, 80, 211, 171))
        self.label.setText("")
        qp = QtGui.QPixmap(os.path.abspath("res/1732856356407-fotor-bg-remover-202411298154.png"))
        self.label.setPixmap(qp)
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.pushButton_login_reg = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton_login_reg.setGeometry(QtCore.QRect(150, 280, 131, 41))
        self.pushButton_login_reg.setStyleSheet("background-color: rgb(0, 153, 81);\n"
"color: white;\n"
"border-radius: 20px;")
        self.pushButton_login_reg.setObjectName("pushButton_login_reg")
        self.pushButton_registration = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton_registration.setGeometry(QtCore.QRect(150, 330, 131, 41))
        self.pushButton_registration.setStyleSheet("background-color: rgb(0, 153, 81);\n"
"color: white;\n"
"border-radius: 20px;")
        self.pushButton_registration.setObjectName("pushButton_registration")
        self.pushButton_forgot = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton_forgot.setGeometry(QtCore.QRect(150, 370, 131, 31))
        self.pushButton_forgot.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.pushButton_forgot.setStyleSheet("border-radius: 20px;\n"
"color: rgb(6, 255, 172);")
        self.pushButton_forgot.setObjectName("pushButton_forgot")
        self.pushButton_forgot.raise_()
        self.label.raise_()
        self.pushButton_login_reg.raise_()
        self.pushButton_registration.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton_login_reg.setText(_translate("Dialog", "Вход"))
        self.pushButton_registration.setText(_translate("Dialog", "Зарегистрироваться"))
        self.pushButton_forgot.setText(_translate("Dialog", "Забыли пароль?"))
