# Form implementation generated from reading ui file 'registration.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(398, 552)
        Dialog.setStyleSheet("background-color: rgb(45, 44, 44);\n"
                             "color: white;\n"
                             "")
        self.lineEdit_password_reg = QtWidgets.QLineEdit(parent=Dialog)
        self.lineEdit_password_reg.setGeometry(QtCore.QRect(120, 300, 161, 30))
        self.lineEdit_password_reg.setStyleSheet("QLineEdit {\n"
                                                 "    border: 2px solid white;\n"
                                                 "    border-radius: 10px;\n"
                                                 "    color: white;\n"
                                                 "\n"
                                                 "}")
        self.lineEdit_password_reg.setText("")
        self.lineEdit_password_reg.setObjectName("lineEdit_password_reg")
        self.label_2 = QtWidgets.QLabel(parent=Dialog)
        self.label_2.setGeometry(QtCore.QRect(120, 230, 47, 13))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=Dialog)
        self.label_3.setGeometry(QtCore.QRect(120, 280, 47, 13))
        self.label_3.setObjectName("label_3")
        self.pushButton_reg_reg = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton_reg_reg.setGeometry(QtCore.QRect(120, 390, 161, 41))
        self.pushButton_reg_reg.setStyleSheet("background-color: rgb(0, 153, 81);\n"
                                              "color: white;\n"
                                              "border-radius: 20px;")
        self.pushButton_reg_reg.setObjectName("pushButton_reg_reg")
        self.lineEdit_login_reg = QtWidgets.QLineEdit(parent=Dialog)
        self.lineEdit_login_reg.setGeometry(QtCore.QRect(120, 250, 161, 30))
        self.lineEdit_login_reg.setStyleSheet("QLineEdit {\n"
                                              "    border: 2px solid white;\n"
                                              "    border-radius: 10px;\n"
                                              "    color: white;\n"
                                              "\n"
                                              "}")
        self.lineEdit_login_reg.setObjectName("lineEdit_login_reg")
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setGeometry(QtCore.QRect(120, 70, 150, 150))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(
            ":/res/kisspng-user-profile-2018-in-sight-user-conference-expo-5b554c0968c377.0307553315323166814291-fotor-bg-remover-20241102121640.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.lineEdit_password2_reg = QtWidgets.QLineEdit(parent=Dialog)
        self.lineEdit_password2_reg.setGeometry(QtCore.QRect(120, 350, 161, 30))
        self.lineEdit_password2_reg.setStyleSheet("QLineEdit {\n"
                                                  "    border: 2px solid white;\n"
                                                  "    border-radius: 10px;\n"
                                                  "    color: white;\n"
                                                  "\n"
                                                  "}")
        self.lineEdit_password2_reg.setText("")
        self.lineEdit_password2_reg.setObjectName("lineEdit_password2_reg")
        self.label_4 = QtWidgets.QLabel(parent=Dialog)
        self.label_4.setGeometry(QtCore.QRect(120, 330, 131, 16))
        self.label_4.setObjectName("label_4")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_2.setText(_translate("Dialog", "Логин"))
        self.label_3.setText(_translate("Dialog", "Пароль"))
        self.pushButton_reg_reg.setText(_translate("Dialog", "Регистрация"))
        self.label_4.setText(_translate("Dialog", "Подтверждение пароля"))
